# Plugins
gems:
- jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["/automation/", "README.md", "LICENCE.txt", "CNAME"]

# Site settings
title: "Vitaliy Zasadnyy"
description: "Hi, my name is Vitaliy, I'm mobile developer and Google Developers Group Lviv co-founder. I'm interested in GameDev, Android, iOS, Google App Engine and community management. Used to work for enterprise giants like EPAM as well as for product companies such as NRavo."
keywords: "developer, geek, google fan, gdg manager"
baseurl: "/personal-site" 
url: "http://zasadnyy-inc.github.io" 

# Analytics
google_analytics_tracking_id: ""
google_analytics_site_url: ""
webtools_site_verification: ""

# Images folders
favicon_folder: "/img/favicons/"
